### ISSUE TITLE
Conceals and Folds

### ISSUE THREAD

**Issue by gleachkr** [junegunn/limelight.vim#1]
This is very cool. I noticed one quirk when working with LaTeX, where there are often some conceals and folds. Here's what it looks like:

![screenshot](https://cloud.githubusercontent.com/assets/6383381/3467861/c48e5830-0296-11e4-8f21-4bc59996131d.png)

The folds are not a big deal, but the conceals are a little distracting. It'd be nice if these could be greyed out too.

**Comment by Hotschke** [comment]
What about the closed folds? I would like to have them greyed out, if I am not with the cursor on the foldtext line.

**Comment by junegunn** [comment]
Unfortunately, I don't think it's possible.
