### ISSUE TITLE
change `Folded` color

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/limelight.vim#13]
Would it be possible to have Limelight change the Folded highlight color when toggling modes?

I just learned I can get the Folded color with `&highlight['f:Folded']` and setting the color is of course easy with `hi Folded ctermfg=Gray` so I added an ugly hack in my goyo Enter/Leave autocmds, but I wonder if this functionality could be added into the plugin itself?

**Comment by junegunn** [comment]
This is related to #1, where I said:

> So, there's no way to selectively gray out conceal chars only in the surrounding paragraphs

I agree that it makes sense to change Folded color but, if we do that, we lose the color in the active paragraph as well. So I'm not sure if we should do this or not.

**Comment by DanielFGray** [comment]
Oh, forgive me for not reading that previous issue.
I suppose that's a fix for NeoVim.
Thank you for your quick responses!
