### ISSUE TITLE
How to integrate with vim easymotion?

### ISSUE THREAD

**Issue by dhanifudin** [junegunn/limelight.vim#14]
![Easymotion when using limelight](https://cloud.githubusercontent.com/assets/6356694/7016530/526f5b96-dd10-11e4-93aa-a9723e129afe.png)

This plugin so great, but when I want to jump to another paragraph using easymotion I can't see target key color.

**Comment by junegunn** [comment]
Hi, I don't use easymotion, so I'm not sure if it's fixable (by limelight). I'll look into it when I get a chance.

**Comment by dhanifudin** [comment]
So, any alternative plugin to replace easymotion (for temporary solution)? What's your workflow to jump to another location?

**Comment by junegunn** [comment]
I just use `/`-search (and `?`) most of the time. [sneak.vim](https://github.com/justinmk/vim-sneak) can be an alternative to easymotion. (I haven't used either extensively.)

**Comment by junegunn** [comment]
And of course, `hjkl`, `wWbBeE`, and some `{}`. They are actually faster than any other clever tricks for short-to-mid distance movement.

**Comment by dhanifudin** [comment]
after try sneak.vim, I can't find this issue. It's seems sneak.vim use default magenta color instead of colorscheme. Maybe movement using default map faster, but I can't remember all different map and usage.

**Comment by SephVelut** [comment]
I have easymotion and I don't have this problem. Must have been miraculously fixed.

**Comment by dhanifudin** [comment]
@SephVelut yes, you're right.
