### ISSUE TITLE
Weird error in neovim

### ISSUE THREAD

**Issue by Randuin** [junegunn/limelight.vim#16]
Getting `Vim(return):E488: Trailing characters` in neovim

**Comment by junegunn** [comment]
Cannot reproduce on my machine. Please provide the minimal vimrc that can be used to reproduce the problem.

**Comment by kuntau** [comment]
I think this is neovim issue because I use the same vimrc for both and error only on neovim

**Comment by junegunn** [comment]
So it's related to this: https://github.com/junegunn/goyo.vim/issues/71

I haven't had time to set up Neovim with truecolor terminal.

**Comment by regnat** [comment]
It's related to neovim no handling `synIDattr()` as it should : `synIDattr(id, 'fg#')` (called [there](https://github.com/junegunn/limelight.vim/blob/master/autoload/limelight.vim#L139)) returns the name of the color and not the hex code, which causes the `s:hex2rgb` function to crash [here](https://github.com/junegunn/limelight.vim/blob/master/autoload/limelight.vim#L149).

A quick workaround waiting for this bug to be patched upstream would be to force neovim to be handled as terminal vim even with true colors.

**Comment by ahmedelgabri** [comment]
Any updates on neovim with true color support? The plugin now doesn't do anything at all, even if `g:limelight_conceal_guifb` is set.

**Comment by junegunn** [comment]
@ahmedelgabri Should work now.

**Comment by ahmedelgabri** [comment]
Thanks @junegunn

**Comment by evantravers** [comment]
I'm getting this error again… running neovim with truecolors in iTerm 2: https://gist.github.com/evantravers/97d6e5e8d8ccdd93be5a2acec6926e46

**Comment by junegunn** [comment]
@evantravers Make sure to upgrade Neovim. Note that [this variable](https://gist.github.com/evantravers/97d6e5e8d8ccdd93be5a2acec6926e46#file-init-vim-L81) is now deprecated in Neovim. Also check out #33.

**Comment by evantravers** [comment]
Thanks @junegunn! You are right.

**Comment by digression99** [comment]
I also had same issues when I trigger `:Limelight`, and I solved by putting `set termguicolors` on my vimrc.
