### ISSUE TITLE
Exclude certain highlight groups (Search/IncSearch)

### ISSUE THREAD

**Issue by frace** [junegunn/limelight.vim#21]
Currently with limelight being enabled it is not possible to spot all results during a live search or the final search results. Only results being inside the "limelighted" paragraph range are visible.

So would it be possible to exclude certain highlight groups from being "dimmed"? In that secific case I do talk about `Search` and `IncSearch` highlight groups.

**Comment by junegunn** [comment]
Thanks for the suggestion. You can now set `g:limelight_priority` to -1 not to overrrule `hlsearch`. See `:help matchadd` for details.

**Comment by frace** [comment]
Thank you very much for the quick enhancement!
