### ISSUE TITLE
Support for cursorbind

### ISSUE THREAD

**Issue by isovector** [junegunn/limelight.vim#25]
Is it possible for a cursorbound window to work in limelight mode? I'm making transformations in one file given an example of a transformation in another. Currently limelight only updates when I switch to the reference window.

**Comment by junegunn** [comment]
```vim
function! s:sync_limelight(bang)
  execute 'Limelight'.a:bang
  augroup sync_limelight
    autocmd!
    if empty(a:bang)
      autocmd CursorMoved * wincmd p | doautocmd limelight CursorMoved | wincmd p
    endif
  augroup END
endfunction

command! -bang SyncLimelight call s:sync_limelight('<bang>')
```

This is hacky, but it seems to work.

**Comment by isovector** [comment]
Fantastic! Works like a charm. Thanks!
