### ISSUE TITLE
Can :Limelight be a toggle?

### ISSUE THREAD

**Issue by gfixler** [junegunn/limelight.vim#26]
`:Goyo` is a toggle, but `:Limelight` requires `:Limelight!` for deactivation. Is it possible to make `:Limelight` work as a toggle?

**Comment by junegunn** [comment]
Any problem [using `:Limelight!!`](https://github.com/junegunn/limelight.vim#usage) ?

**Comment by gfixler** [comment]
No, that works great. Thanks!

**Comment by aemonge** [comment]
It's not working for me .... :(

**Comment by JesseLeite** [comment]
Why have different usage between `:Goyo` toggle and `:Limelight!!` toggle though?

**Comment by junegunn** [comment]
I also don't like the inconsistency, but it's because of backward compatibility. Goyo was written long before Limelight.

**Comment by JesseLeite** [comment]
Ah gotcha.  Well not sure how to deal with breaking changes in vim plugins, but +1 for consistency 👍   ...Especially since you say they pair well together in your readmes 😊
