### ISSUE TITLE
cmder (ConEmu) not supported

### ISSUE THREAD

**Issue by tylerl0706** [junegunn/limelight.vim#29]
I really want to get this plugin working as it looks awesome. Tried in cmder (ConEmu) with no luck. It says "Unsupported Terminal."

Any love for Windows?

**Comment by junegunn** [comment]
This plugin only supports 256-color terminals. I have no experience with ConEmu and don't know if it's possible to enable 256-color on it.

**Comment by tylerl0706** [comment]
Thanks for the speedy reply. I managed to get it to work.

For future reference this link saved the day: 

http://stackoverflow.com/questions/14315519/conemu-vim-syntax-highlight/14434531#14434531

Cheers

**Comment by junegunn** [comment]
Thanks for sharing.
