### ISSUE TITLE
Doesn't work with :set termguicolors

### ISSUE THREAD

**Issue by ibruckelmann** [junegunn/limelight.vim#30]
I reproduced this problem in both vim and neovim.
When set termguicolors in my .vimrc Limelight doesn't work.
It complains that I didn't set limelight_conceal_ctermfg. After I do, it doesn't send out an error message anymore but Limelight still doesn't work.
Neither does it work when I also set limelight_conceal_guifg.

Thanks in advance.

**Comment by junegunn** [comment]
Should be fixed now. Thanks.
