### ISSUE TITLE
Not working on Neovim

### ISSUE THREAD

**Issue by taq** [junegunn/limelight.vim#33]
I just got an error when running this plugin on Neovim.  Seems that there is an error on the `hex2rgb` function, because is not send an hex value there. I forced `synIDattr` to use the `gui` mode (last parameter) and the error stopped, but I still can't have the dimmed parts of the code.

**Comment by taq** [comment]
Hello? :-)

**Comment by junegunn** [comment]
The error only occurs when `termguicolors` is set. But it works fine on regular Vim with the option.

```vim
colo seoul256
echo synIDattr(synIDtrans(hlID('Normal')), 'fg#')
" vim: 252, nvim: 252
set termguicolors
echo synIDattr(synIDtrans(hlID('Normal')), 'fg#')
" vim: #d9d9d9, nvim: 252
```

@justinmk Any idea why I see different results?

**Comment by taq** [comment]
Maybe is Neovim returning it wrong?

**Comment by taq** [comment]
Does regular Vim has the `set termguicolors`?

**Comment by junegunn** [comment]
Yes.
https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162

**Comment by justinmk** [comment]
@junegunn @taq  What version of Neovim ? There was a patch related to this not long ago.

**Comment by taq** [comment]
I use the latest version from the Neovim PPA. They update it almost every
day.

**Comment by justinmk** [comment]
When are you calling `set termguicolors`? 

    nvim --cmd 'set termguicolors' -c "put =synIDattr(synIDtrans(hlID('Normal')), 'fg#')"

Inserts `#f8f8f2` for me. `set termguicolors` must be called during startup (in your vimrc/init.vim), not after. This is a nvim limitation.

**Comment by taq** [comment]
I think is on some script or even a color scheme. I'm away from the
computer (thanks God I can have some hours off sometimes) but I'll test put
it on startup tomorrow and give and answer here.

**Comment by taq** [comment]
Hey, using `set termguicolors` on startup worked, thanks!
