### ISSUE TITLE
W19: Deleting augroup that is still in use

### ISSUE THREAD

**Issue by lifepillar** [junegunn/limelight.vim#36]
I get the warning in the subject every time I leave Goyo. This is my configuration:

- vimrc:

```
    set t_8f=^[[38;2;%lu;%lu;%lum
    set t_8b=^[[48;2;%lu;%lu;%lum
    set termguicolors

    fun! s:goyoEnter()
      Limelight
    endf

    fun! s:goyoLeave()
      Limelight!
    endf

    autocmd! User GoyoEnter nested call <sid>goyoEnter()
    autocmd! User GoyoLeave nested call <sid>goyoLeave()
```

- Vim 7.4.2355, OS X 10.11, iTerm2, [Solarized 8](https://github.com/lifepillar/vim-solarized8), current master of Goyo and Limelight.

**Comment by lifepillar** [comment]
To reproduce it with a minimal vimrc, you may need to call `:colorscheme` at least once (no idea why).

**Comment by junegunn** [comment]
Yeah, I also see the message. However I can't really understand why Vim is complaining when Limelight properly removes autocmds before trying to delete the group (see https://github.com/junegunn/limelight.vim/blob/master/autoload/limelight.vim#L240-L243). This could be a bug of Vim and I'm seeing the same problem in other plugins as well. I'll investigate when I get some time. Thanks.

**Comment by lifepillar** [comment]
It may be worth following this thread on vim-dev: https://groups.yahoo.com/neo/groups/vimdev/conversations/topics/93148

**Comment by lifepillar** [comment]
Eventually it was a Vim bug, fixed with https://github.com/vim/vim/releases/tag/v7.4.2300. You may close this.

**Comment by junegunn** [comment]
I see, thanks for the follow-up.
