### ISSUE TITLE
Error starting limelight

### ISSUE THREAD

**Issue by mpavan** [junegunn/limelight.vim#41]
When I try :LimeLight in my vim, it gives me the following error:

> Unsupported color scheme. g:limelight_conceal_ctermfg required.

Environment:

Mac OS Sierra
iterm2 3.0.15
vim version 7.4.8056
Terminal type: xterm-256color, Unicode

Any help is appreciated. Thanks!

**Comment by elmerehbi** [comment]
I am facing this too on:

Ubuntu Gnome 16.04 LTS
Guake, Terminator, Gnome-terminal, & xterm

PS: I am using the Ultimate Vimrc

**Comment by junegunn** [comment]
Please refer to the following links:
- https://github.com/junegunn/limelight.vim#options
- https://github.com/junegunn/limelight.vim/search?q=g%3Alimelight_conceal_ctermfg&type=Issues&utf8=%E2%9C%93
