### ISSUE TITLE
Error: Traling Character

### ISSUE THREAD

**Issue by piotryordanov** [junegunn/limelight.vim#42]
Hello,

I just installed `limelight`, and when I run it with `:Limelight` i get an error:
```
Vim(return):E488: Trailing Character
```

This even happens when `Goyo` is running.

I have no clue how to debug it! How can I fix it?

**Comment by junegunn** [comment]
I can't reproduce. Check out `:help E488` and see if it gives you some hints.

**Comment by piotryordanov** [comment]
it says: `An argument has been added to an Ex command that does not permit one.`

I have no clue what that means :P

**Comment by junegunn** [comment]
`vim +Limelight` works, right? I believe it's a configuration issue.

**Comment by piotryordanov** [comment]
no it doesn't work. I'm actually using `neovim`, so not sure if that has an impact on the performance.

What could be the configu issue about?

**Comment by junegunn** [comment]
I can't help you with that. You can comment out settings and plugins until it works, to find out the culprit.
