### ISSUE TITLE
Where to define `g:limelight_conceal_ctermfg` ?

### ISSUE THREAD

**Issue by dskesler** [junegunn/limelight.vim#54]
I am receiving the error `Unsupported color scheme. g:limelight_conceal_ctermfg required`. I see in the limelight-vim documentation "you need to define g:limelight_conceal_ctermfg or g:limelight_conceal_guifg." 

Where do I do define these variables? In the plugin file? In the .vimrc? Thank you for any suggestions.

**Comment by junegunn** [comment]
In .vimrc.
