### ISSUE TITLE
Backward range

### ISSUE THREAD

**Issue by gudbjornv** [junegunn/limelight.vim#64]
I get this error when I try to use the keymappings:

"Error detected while processing function limelight#operator:
E493: Backward range given:   '[,']call limelight#execute(0, 1)"

I am relatively new to this all so if this is a common problem caused by my stupidity I do apologize.

I just copied the nmap and xmap keymappings from the README.

**Comment by junegunn** [comment]
There was a bug in the normal mode map. I just fixed it in 2adb5e2caccd682b6043e1a9bc6105da495b1896.
See if this helps in your case.

**Comment by gudbjornv** [comment]
No longer get the error after updating, but now when I toggle it using keybinding it only highlights one line and does'nt change when I move between lines/paragraphs.
[See here.](https://imgur.com/gallery/PE9SQdQ)

**Comment by junegunn** [comment]
Yep, that's expected. It implements a normal-mode operator you can combine with a motion. e.g. `<leader>lip`, `<leader>lG`, etc. If you're not familiar with the concept, just use `:Limelight` command instead of using the map. Or something like `nnoremap <Leader>l :Limelight!!<cr>`.
